### ISSUE TITLE
Strict: Static function SpryngPaymentsApiPhp\Helper::fill() should not be abstract

### ISSUE THREAD

**Issue by dmitry-fedyuk** [spryngpayments/php#1]
https://github.com/spryngpayments/php/blob/0cc2e15/src/Complexity/SpryngPaymentsApiPhp/Helper.php#L19
PHP 5.6.22

**Comment by Roemerb** [comment]
Hi Dmitry, I saw the changes you made at `mage2pro/spryng-sdk`, why would you like this to be changed? The abstract class is implemented by the classes in `Processors/`

**Comment by dmitry-fedyuk** [comment]
https://www.google.com/search?q=PHP+Static+function+should+not+be+abstract

**Comment by Roemerb** [comment]
@dmitry-fedyuk Ah, feel free to open a PR 👍
