### ISSUE TITLE
The \SpryngPaymentsApiPhp\Controller\TransactionController class misses a method to void (reverse) a preauthorized transaction (the «voidAuthTransaction» API call)

### ISSUE THREAD

**Issue by dmitry-fedyuk** [spryngpayments/php#5]
https://api.spryngpayments.com/v1/#operation/voidAuthTransaction

https://github.com/spryngpayments/php/blob/1aa20a7a4e9/src/Complexity/SpryngPaymentsApiPhp/Controller/TransactionController.php

**Comment by Roemerb** [comment]
The library is still in progress.
